-- ============================================================================
-- AMORÇAGE DES FLUX DE L'ÉTAGE 2 — N. Castillo, 25.08.2026. FICHIER GÉNÉRÉ.
--
-- POURQUOI IL EXISTE. L'audit d'automatisation du 25.08 a montré que la table
-- `flux_sources` n'était semée nulle part ailleurs que par un script exécuté à
-- la main (`collecte_flux.py --charger`, depuis un descripteur JSON). Un
-- déploiement neuf — rejouer les migrations, importer les workflows — serait
-- donc parti avec une table VIDE, et le collecteur de flux n'aurait rien eu à
-- collecter sans qu'aucune erreur ne le dise.
--
-- Cette migration rend l'amorçage reproductible. Elle est GÉNÉRÉE DEPUIS LA
-- BASE, qui fait foi depuis que la qualification des seize flux y a été portée
-- nominativement le 24.08 : le descripteur JSON, lui, ne connaît ni les statuts
-- ni les notes de qualification.
--
-- LES STATUTS SONT REPRODUITS TELS QUELS. Onze flux actifs, cinq écartés — les
-- quatre de marchés financiers (symboles inaccessibles) et l'ancien flux
-- automobile, remplacé par sa version au CPV affiné et conservé en preuve.
-- Rejouer cette migration sur une base neuve reconstitue donc l'état qualifié,
-- pas un état par défaut qu'il faudrait requalifier.
--
-- ON CONFLICT DO NOTHING : la migration est rejouable sans écraser une
-- qualification postérieure.
-- ============================================================================

BEGIN;

INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('gdelt_aerospatial', 'actualite', 'aerospatial', 'GDELT — actualité aérospatiale (commandes, cadences, lancements)', 'https://api.gdeltproject.org/api/v2/doc/doc', E'{"_note": "Requête simplifiée le 23.08.2026, même motif que gdelt_medical. Répond 200 avec 49 articles, vérifié en réponse réelle le 23.08.2026. Bruit visible dans les intitulés (aviation de loisir, analyse boursière) : c''est au triage de le trancher, et le taux constaté sera une mesure.", "limite": 50, "fenetre": "7d", "requete": "(\\"aircraft orders\\" OR \\"aerospace supplier\\" OR \\"aircraft production\\")", "requete_statut": "simplifiee_23.08.2026", "requete_anterieure": "(aerospace (orders OR \\"production rate\\" OR supplier) OR \\"aircraft orders\\")"}'::jsonb, 'actif', 'N. Castillo', '2026-08-24'::date, 'GDELT DOC 2.0, requête SIMPLIFIÉE, même réserve que gdelt_medical. Vue en réponse réelle le 23.08.2026, 49 articles, dont plusieurs manifestement hors sujet (aéroports, titres boursiers) — la charge de tri retombe sur le triage IA et l''examen humain.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('gdelt_automobile', 'actualite', 'automobile', 'GDELT — actualité de la filière automobile (production, électrification)', 'https://api.gdeltproject.org/api/v2/doc/doc', E'{"limite": 50, "fenetre": "7d", "requete": "(\\"car production\\" OR \\"auto parts\\" OR \\"vehicle manufacturing\\" OR \\"EV production\\")"}'::jsonb, 'actif', 'N. Castillo', '2026-08-24'::date, 'GDELT DOC 2.0, requête sectorielle. Vue en réponse réelle le 22.08.2026, 50 articles.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('gdelt_horlogerie', 'actualite', 'horlogerie', 'GDELT — actualité mondiale de l''industrie horlogère', 'https://api.gdeltproject.org/api/v2/doc/doc', E'{"limite": 50, "fenetre": "7d", "requete": "(\\"swiss watch industry\\" OR \\"watch exports\\" OR \\"horlogerie suisse\\")"}'::jsonb, 'actif', 'N. Castillo', '2026-08-24'::date, 'GDELT DOC 2.0. Vue en réponse réelle le 22.08.2026, 11 articles seulement — le vocabulaire horloger est peu représenté dans le corpus de presse indexé. Retenu malgré le faible rendement : une absence mesurée vaut mieux qu''une absence supposée.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('gdelt_medical', 'actualite', 'medical', 'GDELT — actualité medtech (réglementation, investissements)', 'https://api.gdeltproject.org/api/v2/doc/doc', E'{"_note": "Requête simplifiée le 23.08.2026 (décision d''étudiant, notes de rédaction). L''ancienne, à parenthèses imbriquées, était refusée en permanence par la limite de cadence de GDELT (« larger queries »), après quatre paliers d''attente 20/40/60/90 s. La simplifiée répond 200 avec 50 articles, vérifié en réponse réelle le 23.08.2026.", "limite": 50, "fenetre": "7d", "requete": "(\\"medical device\\" OR \\"medical devices\\" OR medtech)", "requete_statut": "simplifiee_23.08.2026", "requete_anterieure": "(\\"medical device\\" (regulation OR investment OR manufacturing OR recall))"}'::jsonb, 'actif', 'N. Castillo', '2026-08-24'::date, 'GDELT DOC 2.0, requête SIMPLIFIÉE. Vue en réponse réelle le 23.08.2026, 50 articles. Réserve à porter au rapport : la requête précise, à parenthèses imbriquées, a été refusée durablement par le service (limitation de débit renvoyée en HTTP 200 avec corps non-JSON) ; la version simplifiée est un compromis dont la précision est moindre — les articles rendus ne sont pas tous pertinents.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('boeing_communiques', 'communications', 'aerospatial', 'Boeing — communiqués de presse (fil RSS)', 'https://boeing.mediaroom.com/news-releases-statements?pagetemplate=rss', '{"_note": "Ajouté le 23.08.2026 — famille F2 du protocole OSINT, prévue en vague A par CONCEPTION_ETAGE2.md mais jamais implémentée : aucun descripteur ne la portait. Vérifié en réponse réelle le 23.08 (fil RSS valide, communiqués datés). AIRBUS ÉCARTÉ à la reconnaissance : son /rss.xml répond 200 mais ne sert que la navigation du site (« Environment », « Society »), pas les communiqués — un flux qui répond n''est pas pour autant un flux exploitable. Safran 403, Stryker 404, Medtronic sert du HTML, Swatch Group en délai d''attente, ACEA rend un fil vide."}'::jsonb, 'actif', 'N. Castillo', '2026-08-24'::date, 'Fil de syndication des communiqués Boeing. Vu en réponse réelle le 23.08.2026, 5 items. Source primaire de constructeur : ce qu''elle publie est daté et attribuable, ce qui la distingue des reprises de presse.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('marches_aerospatial', 'marches_financiers', 'aerospatial', 'Cours des donneurs d''ordre aérospatiaux — variation hebdomadaire', 'https://stooq.com/q/d/l/', '{"tickers": ["air.fr", "saf.fr", "ba.us"], "tickers_statut": "a_verifier_symboles_stooq", "fenetre_seances": 5, "seuil_variation_pct": 5.0}'::jsonb, 'ecarte', 'N. Castillo', '2026-08-23'::date, 'Semé par collecte_flux.py --charger (vague A) ; qualification humaine requise avant activation | ÉCARTÉ le 23.08.2026 (décision tracée en notes de rédaction) : Stooq impose une vérification de navigateur par preuve de travail JavaScript, non contournée par principe (CGU, protocole OSINT). Blocage au niveau de la source : les symboles n''ont pu être ni confirmés ni infirmés. Repli Yahoo Finance écarté (429, CGU restrictives). Une API de cours à clé gratuite serait une piste de vague C, non instruite à ce jour.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('marches_automobile', 'marches_financiers', 'automobile', 'Cours des donneurs d''ordre automobiles — variation hebdomadaire', 'https://stooq.com/q/d/l/', '{"tickers": ["vow3.de", "stla.us"], "tickers_statut": "a_verifier_symboles_stooq", "fenetre_seances": 5, "seuil_variation_pct": 5.0}'::jsonb, 'ecarte', 'N. Castillo', '2026-08-23'::date, 'Semé par collecte_flux.py --charger (vague A) ; qualification humaine requise avant activation | ÉCARTÉ le 23.08.2026 (décision tracée en notes de rédaction) : Stooq impose une vérification de navigateur par preuve de travail JavaScript, non contournée par principe (CGU, protocole OSINT). Blocage au niveau de la source : les symboles n''ont pu être ni confirmés ni infirmés. Repli Yahoo Finance écarté (429, CGU restrictives). Une API de cours à clé gratuite serait une piste de vague C, non instruite à ce jour.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('marches_horlogerie', 'marches_financiers', 'horlogerie', 'Cours des donneurs d''ordre horlogers — variation hebdomadaire', 'https://stooq.com/q/d/l/', '{"tickers": ["uhr.sw", "cfr.sw"], "tickers_statut": "a_verifier_symboles_stooq", "fenetre_seances": 5, "seuil_variation_pct": 5.0}'::jsonb, 'ecarte', 'N. Castillo', '2026-08-23'::date, 'Semé par collecte_flux.py --charger (vague A) ; qualification humaine requise avant activation | ÉCARTÉ le 23.08.2026 (décision tracée en notes de rédaction) : Stooq impose une vérification de navigateur par preuve de travail JavaScript, non contournée par principe (CGU, protocole OSINT). Blocage au niveau de la source : les symboles n''ont pu être ni confirmés ni infirmés. Repli Yahoo Finance écarté (429, CGU restrictives). Une API de cours à clé gratuite serait une piste de vague C, non instruite à ce jour.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('marches_medical', 'marches_financiers', 'medical', 'Cours des donneurs d''ordre medtech — variation hebdomadaire', 'https://stooq.com/q/d/l/', '{"tickers": ["syk.us", "mdt.us"], "tickers_statut": "a_verifier_symboles_stooq", "fenetre_seances": 5, "seuil_variation_pct": 5.0}'::jsonb, 'ecarte', 'N. Castillo', '2026-08-23'::date, 'Semé par collecte_flux.py --charger (vague A) ; qualification humaine requise avant activation | ÉCARTÉ le 23.08.2026 (décision tracée en notes de rédaction) : Stooq impose une vérification de navigateur par preuve de travail JavaScript, non contournée par principe (CGU, protocole OSINT). Blocage au niveau de la source : les symboles n''ont pu être ni confirmés ni infirmés. Repli Yahoo Finance écarté (429, CGU restrictives). Une API de cours à clé gratuite serait une piste de vague C, non instruite à ce jour.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('ted_aerospatial', 'marches_publics', 'aerospatial', 'Avis TED — aéronefs, engins spatiaux et équipements associés', 'https://api.ted.europa.eu/v3/notices/search', '{"cpv": "34700000", "_note": " | 23.08.2026 : fenêtre portée de 7 à 30 jours (décision de l''étudiant). L''API TED est libre et le volume mensuel reste modeste ; la fenêtre courte privait la file d''examen de matière. Limite portée à 100 : le volume mensuel de ce CPV tient sous ce plafond, la fenêtre n''est donc pas tronquée par la limite.", "limite": 100, "cpv_statut": "a_verifier", "fenetre_jours": 30}'::jsonb, 'actif', 'N. Castillo', '2026-08-24'::date, 'CPV 34700000 (aéronefs et engins spatiaux). Décompte vérifié en réponse réelle le 23.08.2026, 75 items. Alimente S7 (comptage mensuel). Réserve : la lecture décisionnelle du 24.08 n''y a trouvé aucun avis adressable — les avis relèvent d''achat d''appareils complets, de MRO et de distribution, non de sous-traitance d''usinage.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('ted_automobile', 'marches_publics', 'automobile', 'Avis TED — véhicules et pièces (division 34.3)', 'https://api.ted.europa.eu/v3/notices/search', '{"cpv": "34300000", "_note": "CONSERVÉ EN PREUVE (décision du 23.08.2026). Le CPV 34300000 capte l''ensemble de la branche « parties et accessoires », y compris les pneumatiques et — surtout — les marchés d''entretien de flottes où il n''est qu''un code secondaire derrière 50110000/50100000. Triage du 22.08 : 49 items sur 50 notés 0, taux de rétention 2 %. Ce flux n''est pas corrigé : il documente la vigilance F3 du protocole OSINT (« bruit élevé, tri indispensable ») confirmée sur pièces. Remplacé en exploitation par ted_automobile_v2. | 23.08.2026 : fenêtre portée de 7 à 30 jours (décision de l''étudiant). L''API TED est libre et le volume mensuel reste modeste ; la fenêtre courte privait la file d''examen de matière. Limite maintenue à 50 : le volume mensuel de ce CPV se compte en centaines (automobile large) ou en milliers (médical), et la file d''examen humaine ne s''inonde pas — la limite mord donc avant la fenêtre, ce qui est assumé.", "limite": 50, "cpv_statut": "a_verifier", "fenetre_jours": 30}'::jsonb, 'ecarte', 'N. Castillo', '2026-08-24'::date, 'CPV 34300000 (pièces et accessoires pour véhicules), trop large : la lecture décisionnelle y a trouvé un avis adressable sur 39. Remplacé par ted_automobile_v2 aux CPV affinés le 23.08.2026. Écarté de la collecte, CONSERVÉ EN PREUVE : les 250 avis déjà en base établissent la comparaison avant/après affinage.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('ted_automobile_v2', 'marches_publics', 'automobile', 'Avis TED — moteurs et pièces mécaniques automobiles (CPV 34310/34312/34320)', 'https://api.ted.europa.eu/v3/notices/search', '{"cpv": "34310000, 34312000, 34320000", "_note": "CPV affiné le 23.08.2026 (décision d''étudiant). Analyse de 250 avis sur 30 jours : sous 34300000, les pneumatiques (34350/34351/34352) pèsent 82 avis et l''entretien de flottes 38 — ni l''un ni l''autre ne relève de l''usinage de précision. Le jeu retenu cible les pièces mécaniques usinées : 34310000 moteurs et pièces de moteurs, 34312000 pièces de moteurs, 34320000 pièces de rechange mécaniques hors moteurs. Volume divisé par six (11 avis sur 7 jours contre 70) et intitulés vérifiés en réponse réelle : « Moteurs et pièces de moteurs (véhicules) », « Pièces de moteurs », « Pièces de rechange mécaniques, excepté moteurs et parties de moteurs ». LEVIER LAISSÉ OUVERT : ajouter 34330000 (pièces de rechange pour véhicules) porterait le volume à 20 avis sur 7 jours, au prix d''un élargissement générique — non retenu, à rouvrir si le flux se révèle trop maigre. | 23.08.2026 : fenêtre portée de 7 à 30 jours (décision de l''étudiant). L''API TED est libre et le volume mensuel reste modeste ; la fenêtre courte privait la file d''examen de matière. Limite portée à 100 : le volume mensuel de ce CPV tient sous ce plafond, la fenêtre n''est donc pas tronquée par la limite.", "limite": 100, "cpv_statut": "affine_23.08.2026_verifie_en_intitules", "fenetre_jours": 30}'::jsonb, 'actif', 'N. Castillo', '2026-08-24'::date, 'CPV affinés 34310000, 34312000, 34320000 (moteurs, pièces de moteurs, pièces mécaniques). Vérifiés en réponse réelle le 23.08.2026 : 163 avis sur 60 jours, tous enrichis. Remplace ted_automobile, dont le CPV 34300000 était trop large.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('ted_ferroviaire', 'marches_publics', NULL, 'Avis TED — pièces de locomotives et matériel ferroviaire roulant (CPV 34630000)', 'https://api.ted.europa.eu/v3/notices/search', '{"cpv": "34630000", "_note": "Ajouté le 24.08.2026 sur une DÉCOUVERTE DU DISPOSITIF, non sur une hypothèse : la lecture décisionnelle des 77 appels ouverts n''a retenu que trois avis adressables, et les TROIS étaient des pièces de freins FERROVIAIRES (Roumanie, Hongrie, Italie). Le ferroviaire n''appartient à aucun des quatre marchés surveillés. SECTEUR VOLONTAIREMENT NUL : ajouter un cinquième secteur à la grille est une décision de l''étudiant, pas une conséquence technique. Le flux alimente l''écran Actions sans toucher au cadre du ch. 8. CPV vérifié en intitulés le 24.08 : « Pièces détachées pour locomotives ou matériel ferroviaire roulant », 381 avis sur 60 jours.", "limite": 100, "cpv_statut": "verifie_24.08.2026_en_intitules", "fenetre_jours": 30}'::jsonb, 'actif', 'N. Castillo', '2026-08-24'::date, 'CPV 34630000 (pièces de locomotives et matériel ferroviaire roulant). Vérifié en intitulés sur réponse réelle le 24.08.2026 : 381 avis sur 60 jours, intitulés confirmés comme pièces et non voie ni matériel complet. Ajouté sur découverte du dispositif, non sur hypothèse — les seuls avis usinables des trois autres secteurs étaient ferroviaires. SECTEUR NUL À DESSEIN : l''extension de la grille du ch. 8 à un cinquième marché reste à trancher en supervision.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('ted_medical', 'marches_publics', 'medical', 'Avis TED — équipements et fournitures médicaux (CPV 33)', 'https://api.ted.europa.eu/v3/notices/search', '{"cpv": "33100000", "_note": " | 23.08.2026 : fenêtre portée de 7 à 30 jours (décision de l''étudiant). L''API TED est libre et le volume mensuel reste modeste ; la fenêtre courte privait la file d''examen de matière. Limite maintenue à 50 : le volume mensuel de ce CPV se compte en centaines (automobile large) ou en milliers (médical), et la file d''examen humaine ne s''inonde pas — la limite mord donc avant la fenêtre, ce qui est assumé.", "limite": 50, "cpv_statut": "verifie_20.08.2026_via_M7", "fenetre_jours": 30}'::jsonb, 'actif', 'N. Castillo', '2026-08-24'::date, 'CPV 33100000 (équipements médicaux). Décompte vérifié en réponse réelle TED v3 le 23.08.2026 : 11 752 avis sur 60 jours, 250 enrichis en base. Alimente M7 (comptage mensuel) et l''écran Actions.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('fda_510k_medical', 'reglementaire', 'medical', 'openFDA — autorisations 510(k) de dispositifs médicaux', 'https://api.fda.gov/device/510k.json', '{"_note": "Ajouté le 23.08.2026, chantier des signaux faibles. AMONT AU SENS STRICT : une autorisation de mise sur le marché précède la montée en cadence de production, donc la charge d''usinage, donc toute statistique qui la constatera. Vérifié en réponse réelle le 23.08 : 161 autorisations sur 30 jours, API libre et sans clé. Fenêtre portée de 7 à 30 jours le 23.08 : sur 7 jours la recherche est vide, les décisions étant publiées avec retard.", "limite": 50, "prefixe": "FDA 510(k)", "champ_id": "k_number", "champ_date": "decision_date", "url_detail": "https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpmn/pmn.cfm?ID={ident}", "champ_acteur": "applicant", "champ_libelle": "device_name", "fenetre_jours": 30}'::jsonb, 'actif', 'N. Castillo', '2026-08-24'::date, 'openFDA, point d''accès 510(k), sans clé d''API. Vu en réponse réelle le 23.08.2026, 50 items. Deux particularités de transport documentées et traitées : le séparateur +TO+ des bornes de date ne doit pas être encodé, et un code 404 signifie « aucun résultat », non une erreur. Alimente M8 (comptage mensuel) et la file d''examen.')
ON CONFLICT (flux_id) DO NOTHING;
INSERT INTO flux_sources (flux_id, famille, sector_code, libelle, url_base, parametres, statut, qualified_by, qualified_at, note)
VALUES ('fda_rappels_medical', 'reglementaire', 'medical', 'openFDA — rappels de dispositifs médicaux', 'https://api.fda.gov/device/recall.json', '{"_note": "Ajouté le 23.08.2026. Un rappel signale une défaillance de conception ou de fabrication : c''est un signal de contrainte technique en amont des exigences qui se répercuteront sur les sous-traitants. Volume faible (3 sur 30 jours au 23.08) : fenêtre portée à 30 jours à dessein.", "limite": 50, "prefixe": "FDA rappel", "champ_id": "product_res_number", "champ_date": "event_date_initiated", "url_detail": "", "champ_acteur": "recalling_firm", "champ_libelle": "product_description", "fenetre_jours": 30}'::jsonb, 'actif', 'N. Castillo', '2026-08-24'::date, 'openFDA, point d''accès des rappels de dispositifs. Vu en réponse réelle le 23.08.2026, 3 items sur la fenêtre. Volume faible assumé : un rappel est un événement rare, et c''est précisément sa rareté qui en fait un signal.')
ON CONFLICT (flux_id) DO NOTHING;

COMMIT;

SELECT statut, count(*) AS flux,
       string_agg(flux_id, ', ' ORDER BY flux_id) AS lesquels
FROM flux_sources GROUP BY statut ORDER BY statut;
